site_name: NoSQL Polyglot Persistence Workshop
repo_url: https://github.com/ultimate-engineer/polyglot-nosql
repo_name: ultimate-engineer
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for light mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - content.tabs.link
    - content.code.copy
extra:
  copyright: Copyright &copy; 2023 Elias Nogueira
  social:
    - icon: "fontawesome/brands/github"
      link: "https://github.com/eliasnogueira"
    - icon: "fontawesome/brands/twitter"
      link: "http://twitter.com/eliasnogueira"
    - icon: "fontawesome/brands/linkedin"
      link: "https://linkedin.com/in/eliasnogueira"
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true   
  - admonition
  - pymdownx.details
  - attr_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - md_in_html
nav:
  - "ğŸ  Home": "index.md"
  - "ğŸ› ï¸ Setup": "setup.md"
  - "1. ğŸ“– NoSQL Introduction": "nosql/introduction.md"
  - "2. ğŸš¢ Jakarta EE Overview":
      - "2.1 Introduction": "jakarta-ee/introduction.md"
      - "2.2 Validation": "jakarta-ee/validation.md"
      - "2.3 Lab ğŸ§ª":
          - "2.3.1 Validation": "jakarta-ee/validation-lab.md"
          - "2.3.2 Custom Validation": "jakarta-ee/validation-lab-2.md"
      - "2.4 CDI": "jakarta-ee/cdi.md"
      - "2.5 Lab ğŸ§ª":
          - "2.5.1 CDI Basic 1": "jakarta-ee/cdi-lab-1.md"
          - "2.5.2 CDI Basic 2": "jakarta-ee/cdi-lab-2.md"
      - "2.6 JAX-RS": "jakarta-ee/jax-rs.md"
      - "2.7 Lab ğŸ§ª":
          - "2.7.1 ğŸ§ª JAX-RS Basic": "jakarta-ee/jax-rs-lab.md"
      - "2.8 NoSQL": "jakarta-ee/nosql.md"
      - "2.9 Data": "jakarta-ee/data.md"
  - "ğŸ”‘ 3. Key-Value database":
        - "3.1 Introduction": "key-value/introduction.md" 
        - "3.2 Redis": "key-value/redis.md"
        - "3.3 Redis commands": "key-value/redis-commands.md"
        - "3.4 Lab ğŸ§ª":
            - "3.4.1 Redis Basic": "key-value/database-lab.md"
            - "3.4.2 Redis Java 1": "key-value/java-lab.md"
            - "3.4.3 Redis Java 2": "key-value/java-lab-2.md"
  - "ğŸ“˜ 4. Wide-Column database":
        - "4.1 Introduction": "column/introduction.md" 
        - "4.2 Apache Cassandra": "column/cassandra.md"
        - "4.3 Cassandra Commands": "column/commands.md"
        - "4.4 Lab ğŸ§ª":
            - "4.4.1 Cassandra Basic": "column/database-lab.md"
            - "4.4.2 Cassandra Java 1": "column/java-lab.md"
            - "4.4.3 Cassandra Java 2": "column/java-lab-2.md"
            - "4.4.4 Cassandra Java 3": "column/java-lab-3.md"
  - "ğŸ“• 5. Document database":
        - "5.1 Introduction": "document/introduction.md" 
        - "5.2 MongoDB": "document/mongodb.md"
        - "5.2.1 ğŸ§ª MongoDB Basic": "document/database-lab.md"
        - "5.2.2 ğŸ§ª MongoDB Java": "document/java-lab.md"
  - "ğŸ‘¨â€ğŸ‘¨â€ğŸ‘§â€ğŸ‘§ 6. Graph database":
        - "6.1 Introduction": "graph/introduction.md" 
        - "6.2 Neo4J": "graph/neo4j.md"
        - "6.2.1 ğŸ§ª Neo4J Basic": "graph/database-lab.md"
        - "6.2.2 ğŸ§ª Neo4J Java": "graph/java-lab.md"
        - "6.2.3 ğŸ§ª Neo4J Java": "graph/java-lab-2.md"
        - "6.2.4 ğŸ§ª Neo4J Java": "graph/java-lab-3.md"
  - "ğŸ§ª 7. Extra labs":
      - "7.1 CDI Intermediate": "extra-labs/cdi-lab-3.md"
      - "7.2 CDI After-Intermediate": "extra-labs/cdi-lab-4.md"