site_name: NoSQL Polyglot Persistence Workshop
repo_url: https://github.com/ultimate-engineer/polyglot-nosql
repo_name: ultimate-engineer
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for light mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - content.tabs.link
    - content.code.copy
extra:
  copyright: Copyright &copy; 2023 Elias Nogueira
  social:
    - icon: "fontawesome/brands/github"
      link: "https://github.com/eliasnogueira"
    - icon: "fontawesome/brands/twitter"
      link: "http://twitter.com/eliasnogueira"
    - icon: "fontawesome/brands/linkedin"
      link: "https://linkedin.com/in/eliasnogueira"
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true   
  - admonition
  - pymdownx.details
  - attr_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - md_in_html
nav:
  - "ğŸ  Home": "index.md"
  - "ğŸ› ï¸ Setup": "setup.md"
  - "1. NoSQL Introduction": "nosql/introduction.md"
  - "2. Jakarta EE Overview":
      - "2.1 Introduction": "jakarta-ee/introduction.md"
      - "2.2 Validation": "jakarta-ee/validation.md"
      - "2.2.1 ğŸ§ª Validation": "jakarta-ee/validation-lab.md"
      - "2.2.2 ğŸ§ª Custom Validation": "jakarta-ee/validation-lab-2.md"
      - "2.3 CDI": "jakarta-ee/cdi.md"
      - "2.3.1 ğŸ§ª CDI Basic": "jakarta-ee/cdi-lab.md"
      - "2.3.2 ğŸ§ª CDI Intermediate": "jakarta-ee/cdi-lab-2.md"
      - "2.3.3 ğŸ§ª CDI After-Intermediate": "jakarta-ee/cdi-lab-3.md"  
      - "2.4 JAX-RS": "jakarta-ee/jax.md"
      - "2.4.1 ğŸ§ª JAX-RS Basic": "jakarta-ee/jax-rs-lab.md" 
      - "2.5 NoSQL": "jakarta-ee/nosql.md"
      - "2.6 Data": "jakarta-ee/data.md"
  - "ğŸ”‘ 3. Key-Value database":
        - "3.1 Introduction": "key-value/introduction.md" 
        - "3.2 Redis": "key-value/redis.md"
        - "3.2.1 ğŸ§ª Redis Basic": "key-value/database-lab.md"
        - "3.2.2 ğŸ§ª Redis Java": "key-value/java-lab.md"
        - "3.2.3 ğŸ§ª Redis Java 2": "key-value/java-lab-2.md"
  - "ğŸ“˜ 4. Wide-Column database":
        - "4.1 Introduction": "column/introduction.md" 
        - "4.2 Apache Cassandra": "column/cassandra.md"
        - "4.2.1 ğŸ§ª Apache Cassandra Basic": "column/database-lab.md"
        - "4.2.2 ğŸ§ª Cassandra Java": "column/java-lab.md"
  - "ğŸ“• 5. Document database":
        - "5.1 Introduction": "document/introduction.md" 
        - "5.2 MongoDB": "document/mongodb.md"
        - "5.2.1 ğŸ§ª MongoDB Basic": "document/database-lab.md"
        - "5.2.2 ğŸ§ª MongoDB Java": "key-value/java-lab.md"
  - "ğŸ‘¨â€ğŸ‘¨â€ğŸ‘§â€ğŸ‘§ 6. Graph database":
        - "6.1 Introduction": "graph/introduction.md" 
        - "6.2 Neo4J": "graph/neo4j.md"
        - "6.2.1 ğŸ§ª Neo4J Basic": "graph/database-lab.md"
        - "6.2.2 ğŸ§ª Neo4J Java": "graph/java-lab.md"
